//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanTeenManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ORDERINFOes = new HashSet<ORDERINFO>();
        }
    
        public string ID { get; set; }
        public string PIN { get; set; }
        public string FULLNAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<int> YEAROFBIRTH { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> CASH { get; set; }
        public Nullable<int> POINT { get; set; }
        public string IMAGELINK { get; set; }
        public Nullable<int> STAR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERINFO> ORDERINFOes { get; set; }
    }
}
