//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanTeenManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ORDERINFOes = new HashSet<ORDERINFO>();
        }
    
        public string ID { get; set; }
        public string PASSWORD { get; set; }
        public string FULLNAME { get; set; }
        public string GENDER { get; set; }
        public int YEAROFBIRTH { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string POSITION { get; set; }
        public string ROLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERINFO> ORDERINFOes { get; set; }
    }
}
