//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanTeenManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERINFO()
        {
            this.ORDERDETAILs = new HashSet<ORDERDETAIL>();
        }
    
        public string ID { get; set; }
        public string CUSTOMERID { get; set; }
        public string EMPLOYEEID { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<int> TOTALMONEY { get; set; }
        public string STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILs { get; set; }
    }
}
